import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  section: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 16,
    width: '100%',
  },
  h2: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  resumoDoPedido: {
    fontSize: 18,
    fontWeight: "600",
    fontFamily: "Poppins-SemiBold",
    color: "#000",
    textAlign: "left",
    flex: 1,
  },
  div: {
    width: '100%',
  },
  div1: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  div3: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  productInfo: {
    flexDirection: 'column',
    flex: 1,
    marginRight: 10,
  },
  tomateOrgnico: {
    fontSize: 16,
    fontFamily: "Poppins-Medium",
    fontWeight: "500",
    color: "#000",
    textAlign: "left",
    lineHeight: 20,
  },
  alfaceCrespa: {
    fontSize: 16,
    fontFamily: "Poppins-Medium",
    fontWeight: "500",
    color: "#000",
    textAlign: "left",
    lineHeight: 20,
  },
  xR890kg: {
    fontSize: 14,
    fontFamily: "Poppins-Regular",
    color: "#6b7280",
    textAlign: "left",
    marginTop: 4,
    lineHeight: 18,
  },
  xR350un: {
    fontSize: 14,
    fontFamily: "Poppins-Regular",
    color: "#6b7280",
    textAlign: "left",
    marginTop: 4,
    lineHeight: 18,
  },
  r280: {
    fontSize: 16,
    fontFamily: "Poppins-Medium",
    fontWeight: "500",
    color: "#000",
    textAlign: "right",
    minWidth: 60,
  },
  r350: {
    fontSize: 16,
    fontFamily: "Poppins-Medium",
    fontWeight: "500",
    color: "#000",
    textAlign: "right",
    minWidth: 60,
  },
  div5: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 20,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#eee',
  },
  total: {
    fontSize: 18,
    fontFamily: "Poppins-SemiBold",
    fontWeight: "600",
    color: "#000",
    textAlign: "left",
  },
  r630: {
    fontSize: 18,
    fontFamily: "Poppins-SemiBold",
    fontWeight: "600",
    color: "#000",
    textAlign: "right",
    minWidth: 70,
  },
});