import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  section: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 16,
    width: '100%',
  },
  h2: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  pagamento: {
    fontSize: 18,
    fontWeight: "600",
    fontFamily: "Poppins-SemiBold",
    color: "#000",
    textAlign: "left",
    flex: 1,
  },
  div: {
    width: '100%',
  },
  optionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  radioButton: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 1.5,
    borderColor: "#000",
    marginRight: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  radioButtonSelectedOuter: {
    borderColor: "#255336",
  },
  radioButtonSelectedInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#255336",
  },
  cartoDeCrdito: {
    fontSize: 16,
    fontFamily: "Poppins-Medium",
    fontWeight: "500",
    color: "#000",
  },
  pix: {
    fontSize: 16,
    fontFamily: "Poppins-Medium",
    fontWeight: "500",
    color: "#000",
  },
  dinheiro: {
    fontSize: 16,
    fontFamily: "Poppins-Medium",
    fontWeight: "500",
    color: "#000",
  },
  inputFieldFull: {
    width: '100%',
    height: 42,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 8,
    backgroundColor: "#f9fafb",
    paddingHorizontal: 12,
    paddingVertical: 0,
    textAlignVertical: 'center',
    includeFontPadding: false,
    lineHeight: 42,
    fontSize: 16,
    fontFamily: "Poppins-Regular",
    color: "#000",
    marginBottom: 12,
  },
  cardExpiryCvvRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    width: '100%',
    marginBottom: 12,
  },
  inputFieldHalf: {
    flex: 1,
    height: 42,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 8,
    backgroundColor: "#f9fafb",
    paddingHorizontal: 12,
    paddingVertical: 0,
    textAlignVertical: 'center',
    includeFontPadding: false,
    lineHeight: 42,
    fontSize: 16,
    fontFamily: "Poppins-Regular",
    color: "#000",
  },
  creditCardFields: {
    marginTop: -8,
    marginBottom: 16,
  },
});