import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  card: {
    shadowColor: "rgba(0, 0, 0, 0.05)",
    shadowOffset: { width: 0, height: 1 },
    shadowRadius: 2,
    elevation: 2,
    shadowOpacity: 1,
    borderRadius: 12,
    backgroundColor: "#fff",
    width: "100%",
    height: 160,
  },
  header: {
    position: "absolute",
    top: 16,
    left: 16,
    width: 326,
    height: 48,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 8,
  },
  info: {
    width: 250, 
  },
  name: {
    fontSize: 18,
    lineHeight: 18,
    fontWeight: "600",
    fontFamily: "Poppins-SemiBold",
    color: "#000",
    textAlign: "left",
    width: 200,
  },
  neighborhood: {
    marginTop: 8,
    fontSize: 14,
    lineHeight: 18,
    fontFamily: "Poppins-Regular",
    color: "#6b7280",
    textAlign: "left",
    maxWidth: 150,
  },
  statusContainer: {
    position: "absolute",
    top: 0,
    right: 0,
    width: 57,
    height: 24,
  },
  status: {
    position: "absolute",
    top: 1,
    left: 7,
    borderRadius: 9999,
    width: 70,
    height: 30,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#d1fae5",
  },
  statusOpen: {
    backgroundColor: "#d1fae5",
  },
  statusClosed: {
    backgroundColor: "#fee2e2",
  },
  statusText: {
    fontSize: 12,
    fontFamily: "Poppins-Regular",
    color: "#047857",
    width: 60,
    height: 17,
    textAlign: "center",
  },
  statusTextClosed: {
    color: "#dc2626",
  },
  details: {
    position: "absolute",
    top: 64,
    left: 16,
    width: 326,
    height: 20,
    flexDirection: "row",
  },
  hours: {
    position: "absolute",
    left: 0,
    width: 86,
    flexDirection: "row",
    alignItems: "center",
  },
  distance: {
    position: "absolute",
    left: 98,
    width: 60,
    flexDirection: "row",
    alignItems: "center",
  },
  icon: {
    width: 14,
    height: 14,
    marginRight: 4,
  },
  detailText: {
    fontSize: 14,
    fontFamily: "Poppins-Regular",
    color: "#4b5563",
    maxWidth: 64,
  },
  mapButton: {
    position: "absolute",
    top: 108,
    left: 16,
    width: 340,
    height: 36,
    borderRadius: 8,
    backgroundColor: "#f3f4f6",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  mapButtonText: {
    position: "absolute",
    left: 126,
    fontSize: 14,
    fontFamily: "Poppins-Regular",
    color: "#374151",
    textAlign: "center",
    width: 92,
  },
  mapButtonIcon: {
    position: "absolute",
    left: 108,
    width: 11,
    height: 14,
  },
});

export default styles;