import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  section: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 16,
    width: '100%',
  },
  h2: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  comoDesejaReceber: {
    fontSize: 18,
    fontWeight: "600",
    fontFamily: "Poppins-SemiBold",
    color: "#000",
    textAlign: "left",
    flex: 1,
  },
  div: {
    width: '100%',
  },
  optionRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 20,
  },
  pickupOptionRow: {
    marginBottom: 0,
  },
  radioButton: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 1.5,
    borderColor: "#000",
    marginRight: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 2,
  },
  radioButtonSelectedOuter: {
    borderColor: "#255336",
  },
  radioButtonSelectedInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#255336",
  },
  optionContent: {
    flex: 1,
    flexDirection: 'column',
  },
  entregarNoMeu: {
    fontSize: 16,
    fontFamily: "Poppins-Medium",
    fontWeight: "500",
    color: "#000",
    textAlign: "left",
    lineHeight: 22,
  },
  ruaDasFlores: {
    fontSize: 14,
    fontFamily: "Poppins-Regular",
    color: "#6b7280",
    textAlign: "left",
    marginTop: 2,
    lineHeight: 20,
  },
  button: {
    marginTop: 8,
  },
  editarEndereo: {
    fontSize: 14,
    fontFamily: "Poppins-Regular",
    color: "#059669",
    textAlign: "left",
    textDecorationLine: 'underline',
  },
  retirarNaFeira: {
    fontSize: 16,
    fontFamily: "Poppins-Medium",
    fontWeight: "500",
    color: "#000",
    textAlign: "left",
    lineHeight: 22,
    marginBottom: 10,
  },
  pickupTimeContainer: {
    width: '100%',
    marginTop: 10,
  },
  horarioEstimadoPara: {
    fontSize: 16,
    fontFamily: "Poppins-Medium",
    fontWeight: "500",
    color: "#000",
    textAlign: "left",
    marginBottom: 8,
  },
  select: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: 43,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    paddingHorizontal: 12,
    backgroundColor: "#f9fafb",
  },
  hojeEntre: {
    fontSize: 16,
    fontFamily: "Poppins-Regular",
    color: "#000",
    textAlign: "left",
    flex: 1,
    lineHeight: 22,
  },
  arrowImage: {
    width: 20,
    height: 20,
    resizeMode: 'contain',
    marginLeft: 8,
  },
  dropdownOptions: {
    position: 'absolute',
    top: 43 + 8,
    left: 0,
    right: 0,
    backgroundColor: '#fff',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    zIndex: 10,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  dropdownOptionItem: {
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  dropdownOptionText: {
    fontSize: 16,
    fontFamily: "Poppins-Regular",
    color: "#000",
  },
});